BOARD_TAG = digispark
#ARDUINO_LIBS = <space separated list of libs, arduino.mk will try to guess>
#MONITOR_PORT = /dev/ttyUSB0 (will be automatically guessed from IDE prefs)
BOARDS_TXT = /usr/share/arduino/hardware/digistump/avr/boards.txt
include /usr/share/arduino/Arduino.mk
